# app/agents/tools/search_tool.py
# Knowledge base search tool — wraps VectorClient.
#
# Vector API now returns only CITED chunks (not all retrieved chunks).
# answer_available is the authoritative signal — always check it first.
#
# Tool output format:
#   SEARCH_RESULTS for query: '...'
#   Application identified: Astro        (if single app detected)
#   SOURCES_JSON:[{...}]                 (cited sources for citation UI)
#   ANSWER:
#   {pre-synthesised answer text}
#   SUPPORTING SOURCES (N articles):
#   [Source 1] ...
#
# Agent uses ANSWER as primary — enriches with conversational context.
# NO_RESULTS_FOUND returned when answer_available=False — agent tells user gracefully.

import json
import logging

from langchain_core.tools import tool

from app.agents.clients.vector_client import VectorChunk, vector_client

logger = logging.getLogger(__name__)


def _format_chunk(chunk: VectorChunk, index: int) -> str:
    """
    Formats a cited chunk as a source reference for the agent.
    source_url only included if it starts with http (SharePoint URLs).
    """
    lines = [f"[Source {index + 1}]"]
    if chunk.file_name:
        lines.append(f"File: {chunk.file_name}")
    if chunk.application:
        lines.append(f"Application: {chunk.application}")
    if chunk.source_url and chunk.source_url.startswith("http"):
        lines.append(f"URL: {chunk.source_url}")
    # Include a brief excerpt so agent has context for any gap-filling
    excerpt = chunk.text[:200] + "..." if len(chunk.text) > 200 else chunk.text
    lines.append(f"Excerpt: {excerpt}")
    return "\n".join(lines)


@tool
async def search_knowledge_base(query: str) -> str:
    """
    Search the PwC IT support knowledge base for information related to the query.

    Use this tool when the user asks an IT support question about any PwC application
    or system. The knowledge base contains troubleshooting guides, how-to articles,
    and IT support documentation.

    Call this tool with a clear, specific search query. If the user's question covers
    multiple distinct issues, you may call this tool multiple times with different
    focused queries.

    Do NOT call this tool for:
    - Greetings or casual conversation
    - General knowledge questions unrelated to PwC IT support
    - Questions where you already have sufficient context from previous tool calls

    Args:
        query: A clear, specific search query. Make it standalone — include
               context from conversation history if this is a follow-up question.
               Examples:
                 "SAP login authentication failure"
                 "Workday timesheet submission error"
                 "how to reset password in ServiceNow portal"

    Returns:
        A pre-synthesised answer from the knowledge base along with cited sources,
        or a message indicating no relevant information was found.
    """
    logger.info("search_knowledge_base called — query: %s", query)

    try:
        result = await vector_client.search(query)
    except Exception as e:
        logger.error("Vector search failed: %s", str(e))
        return (
            "SEARCH_ERROR: Knowledge base search failed due to a technical issue. "
            "Inform the user and suggest raising a ServiceNow ticket if urgent."
        )

    # answer_available is the authoritative signal from the API
    # When False: answer=None, chunks=[] — knowledge base has no relevant content
    if not result.answer_available:
        return (
            f"NO_RESULTS_FOUND: No relevant information found in the knowledge "
            f"base for query: '{query}'. "
            "Do not guess or make up information. "
            "Inform the user no information is currently available. "
            "If their issue seems genuine, gently suggest raising a ticket."
        )

    output_parts = [f"SEARCH_RESULTS for query: '{query}'", ""]

    if result.app_identified:
        output_parts.append(f"Application identified: {result.app_identified}")
        output_parts.append("")

    # Embed cited sources as structured JSON for citation extraction by chat.py
    # chat.py reads this from on_tool_end events (ToolMessage.content)
    # All chunks here are cited — no rerank_score filtering needed
    sources_data = [
        {
            "file_name":  chunk.file_name,
            "source_url": chunk.source_url,
            "application": chunk.application or "",
        }
        for chunk in result.chunks
        if chunk.file_name   # skip any chunks without a file name
    ]
    if sources_data:
        output_parts.append(f"SOURCES_JSON:{json.dumps(sources_data)}")
        output_parts.append("")

    # Primary answer — generated by Vector API after full semantic search + synthesis
    # Agent enriches with conversational context but does NOT re-synthesise
    output_parts.extend([
        "ANSWER:",
        result.answer or "",
        "",
        "Use the ANSWER above as the primary basis for your response. "
        "Enrich it with conversational context from the chat history. "
        "Do not re-synthesise from the sources — the answer is already high quality.",
        "",
    ])

    # Supporting sources for agent context (already cited, high quality)
    if result.chunks:
        output_parts.append(f"CITED SOURCES ({result.cited_chunks} articles):")
        for i, chunk in enumerate(result.chunks[:5]):
            output_parts.append(_format_chunk(chunk, i))
            output_parts.append("")

    return "\n".join(output_parts)