# app/agents/tools/search_tool.py
# Knowledge base search tool — wraps VectorClient.
#
# The Vector API answer field is used as PRIMARY answer.
# It is generated after full semantic search + reranking + synthesis.
# Our LLM enriches this with conversational context — does not re-synthesise.
#
# Tool output structure:
#   ANSWER:          → primary answer from Vector API (agent uses this)
#   SUPPORTING SOURCES: → chunks for source attribution only
#
# Agent behaviour based on tool output:
#   has answer       → enrich with context, add ticket link if needed
#   NO_RESULTS_FOUND → inform user, gently suggest ticket
#   SEARCH_ERROR     → inform user, suggest ticket

import logging

from langchain_core.tools import tool

from app.agents.clients.vector_client import VectorChunk, vector_client

logger = logging.getLogger(__name__)


def _format_chunk(chunk: VectorChunk, index: int) -> str:
    """Formats a single chunk as a supporting source reference."""
    lines = [f"[Source {index + 1}]"]
    if chunk.file_name:
        lines.append(f"File: {chunk.file_name}")
    if chunk.application:
        lines.append(f"Application: {chunk.application}")
    if chunk.source_url:
        lines.append(f"URL: {chunk.source_url}")
    lines.append(f"Relevance: {chunk.rerank_score:.2f}")
    # Include a brief excerpt for context
    excerpt = chunk.text[:200] + "..." if len(chunk.text) > 200 else chunk.text
    lines.append(f"Excerpt: {excerpt}")
    return "\n".join(lines)


@tool
async def search_knowledge_base(query: str) -> str:
    """
    Search the XYZ IT support knowledge base for information related to the query.

    Use this tool when the user asks an IT support question about any XYZ application
    or system. The knowledge base contains troubleshooting guides, how-to articles,
    and IT support documentation.

    Call this tool with a clear, specific search query. If the user's question covers
    multiple distinct issues, you may call this tool multiple times with different
    focused queries.

    Do NOT call this tool for:
    - Greetings or casual conversation
    - General knowledge questions unrelated to XYZ IT support
    - Questions where you already have sufficient context from previous tool calls

    Args:
        query: A clear, specific search query. Make it standalone — include
               context from conversation history if this is a follow-up question.
               Examples:
                 "SAP login authentication failure"
                 "Astro timesheet submission error"
                 "how to reset password in ServiceNow portal"

    Returns:
        A pre-synthesised answer from the knowledge base along with supporting
        sources, or a message indicating no relevant information was found.
    """
    logger.info("search_knowledge_base called — query: %s", query)

    try:
        result = await vector_client.search(query)
    except Exception as e:
        logger.error("Vector search failed: %s", str(e))
        return (
            "SEARCH_ERROR: Knowledge base search failed due to a technical issue. "
            "Inform the user and suggest raising a ServiceNow ticket if their "
            "issue is urgent."
        )

    if not result.has_results:
        return (
            f"NO_RESULTS_FOUND: No relevant information found in the knowledge "
            f"base for query: '{query}'. "
            "Do not guess or make up information. "
            "Inform the user that no information is currently available for their "
            "question. If their issue seems genuine, gently suggest they raise a "
            "ticket for further assistance — do not force this."
        )

    # Build output with answer as primary
    output_parts = [
        f"SEARCH_RESULTS for query: '{query}'",
        "",
    ]

    if result.app_identified:
        output_parts.append(f"Application identified: {result.app_identified}")
        output_parts.append("")

    # Primary answer — generated by Vector API after full semantic search + reranking
    if result.answer:
        output_parts.extend([
            "ANSWER:",
            result.answer,
            "",
            "Use the above ANSWER as the primary basis for your response. "
            "Enrich it with conversational context from the chat history. "
            "Do not re-synthesise from sources — the answer is already high quality.",
            "",
        ])

    # Supporting sources for reference
    if result.chunks:
        output_parts.append(
            f"SUPPORTING SOURCES ({len(result.chunks)} articles):"
        )
        for i, chunk in enumerate(result.chunks[:5]):   # max 5 sources shown
            output_parts.append(_format_chunk(chunk, i))
            output_parts.append("")

    return "\n".join(output_parts)